### ISSUE TITLE
Cannot run unpublished version

### ISSUE THREAD

**Issue by naugtur** [juliangruber/browser-run#122]
This commit: 
https://github.com/juliangruber/browser-run/commit/e161817689080d0805022d103582782d8f106454

Introduces a requirement that browser-run can only work if it's installed from npm (or any copy of published version, where `/static/reporter.js` is generated.
Figuring it out took me a while.

I'm not PRing a fix to switch from prepublish to a postinstall because I hope to discuss it first. Since browserify is in devDependencies, is it ok to assume it's there when postinstall is running? Sounds risky.

For people trying to test what they contribute instead of just PRing it, let's at least add an error message that explains what happened when `/static/reporter.js` can't be found

**Comment by naugtur** [comment]
A build that fails when installing browser-run from git: https://travis-ci.org/naugtur/xhr/builds/175333968

**Comment by juliangruber** [comment]
Multiple reasons here:

- it's in prepublish instead of postinstall, so consumers don't need to install browserify
- the build step is in pretest so it happens every time you run the test suite. we could probably add it to the example script too?
- since browserify is in dev deps, it's only going to be installed when you run `npm install` inside this directory, not when you `npm install browser-run`
- +1 on adding a meaningful error message

**Comment by naugtur** [comment]
I'm ok with just the message, that'd save me some time on my first contribution attempt :)
